{
  if ((exception == null) || (exception.getMessage() == null) || (exception.getMessage().indexOf(expected) == -1)) {
    log.log(Level.SEVERE,"wrong exception: ",exception);
    throw new AssertionFailedError("expected presence of '" + expected + "' but was '"+ exception+ "' see logs for the original exception");
  }
}
