{
  ProcessInstance processInstance=runtimeService.startProcessInstanceByKey("exceptionInJobExecution");
  Job timerJob=managementService.createJobQuery().processInstanceId(processInstance.getId()).singleResult();
  assertNotNull("No job found for process instance",timerJob);
  try {
    managementService.executeJob(timerJob.getId());
    fail("RuntimeException from within the script task expected");
  }
 catch (  RuntimeException re) {
    assertTextPresent("This is an exception thrown from scriptTask",re.getMessage());
  }
  timerJob=managementService.createJobQuery().processInstanceId(processInstance.getId()).singleResult();
  assertNotNull(timerJob);
  assertNotNull(timerJob.getExceptionMessage());
  assertTextPresent("This is an exception thrown from scriptTask",timerJob.getExceptionMessage());
  String exceptionStack=managementService.getJobExceptionStacktrace(timerJob.getId());
  assertNotNull(exceptionStack);
  assertTextPresent("This is an exception thrown from scriptTask",exceptionStack);
}
