{
  ProcessInstance processNoException=runtimeService.startProcessInstanceByKey(PROCESS_DEFINITION_KEY_NO_EXCEPTION);
  HistoricProcessInstanceQuery queryNoException=historyService.createHistoricProcessInstanceQuery();
  assertEquals(1,queryNoException.count());
  assertEquals(1,queryNoException.list().size());
  assertEquals(processNoException.getId(),queryNoException.list().get(0).getId());
  HistoricProcessInstanceQuery queryWithException=historyService.createHistoricProcessInstanceQuery();
  assertEquals(0,queryWithException.withException().count());
  assertEquals(0,queryWithException.withException().list().size());
  ProcessInstance processWithException1=startProcessInstanceWithFailingJob(PROCESS_DEFINITION_KEY_WITH_EXCEPTION_1);
  JobQuery jobQuery1=managementService.createJobQuery().processInstanceId(processWithException1.getId());
  assertEquals(1,jobQuery1.withException().count());
  assertEquals(1,jobQuery1.withException().list().size());
  assertEquals(1,queryWithException.withException().count());
  assertEquals(1,queryWithException.withException().list().size());
  assertEquals(processWithException1.getId(),queryWithException.withException().list().get(0).getId());
  ProcessInstance processWithException2=startProcessInstanceWithFailingJob(PROCESS_DEFINITION_KEY_WITH_EXCEPTION_2);
  JobQuery jobQuery2=managementService.createJobQuery().processInstanceId(processWithException2.getId());
  assertEquals(2,jobQuery2.withException().count());
  assertEquals(2,jobQuery2.withException().list().size());
  assertEquals(2,queryWithException.withException().count());
  assertEquals(2,queryWithException.withException().list().size());
  assertEquals(processWithException1.getId(),queryWithException.withException().processDefinitionKey(PROCESS_DEFINITION_KEY_WITH_EXCEPTION_1).list().get(0).getId());
  assertEquals(processWithException2.getId(),queryWithException.withException().processDefinitionKey(PROCESS_DEFINITION_KEY_WITH_EXCEPTION_2).list().get(0).getId());
}
